# SPDX-License-Identifier: Unlicense
FROM quay.io/jupyter/scipy-notebook:2026-02-09
USER ${NB_UID}
COPY requirements/jupyter.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
