FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev wget ca-certificates \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    mlflow==3.4.0 \
    psycopg2-binary==2.9.10 \
    boto3==1.40.36 \
    gunicorn==23.0.0

EXPOSE 5000
ENTRYPOINT ["mlflow"]
